### ISSUE TITLE
problem with regions to select

### ISSUE THREAD

**Issue by adjebbar** [zhenrong-wang/hpc-now#36]
Hey there. 

I still facing the problem of zone and region to specify to initialise a new cluster. hpcopr init -b with version :  0.3.1.0129
[Screenshot from 2024-03-20 23-32-26](https://github.com/zhenrong-wang/hpc-now/assets/45851643/002bac40-6a5f-48e0-91b8-71a2a44a54c9)

[ FATAL: ] TF_EXEC_ERROR.3 min(s). 107 sec(s) passed ... (-)
[ FATAL: ] Failed to operate the cluster. Operation command: apply.
Any help !
Thanks.

**Comment by adjebbar** [comment]
I still need to add --rg eu-west-3

**Comment by zhenrong-wang** [comment]
> I still need to add --rg eu-west-3

1. Could you please upload the error log info here?

2. Have you tried us-east-1? If it works with us-east-1, the problem may comes from the AWS back end. Anyway, I will check eu-west-3 from my side.

Thanks!

**Comment by zhenrong-wang** [comment]
> I still need to add --rg eu-west-3

Yes - we provide one default region and currently it is not configurable. 

For AWS, the default region is us-east-1. If you'd like to create a cluster in any region, you need to specify --rg explicitly.

And please pull the latest code and retry.

**Comment by zhenrong-wang** [comment]
> Hey there. 
> 
> I still facing the problem of zone and region to specify to initialise a new cluster. hpcopr init -b with version :  0.3.1.0129
> [Screenshot from 2024-03-20 23-32-26](https://github.com/zhenrong-wang/hpc-now/assets/45851643/002bac40-6a5f-48e0-91b8-71a2a44a54c9)
> 
> [ FATAL: ] TF_EXEC_ERROR.3 min(s). 107 sec(s) passed ... (-)
> [ FATAL: ] Failed to operate the cluster. Operation command: apply.
> Any help !
> Thanks.

Could you please print and provide the error log info here?

There are several possibilities. For example, AWS restricts the scale of instances for new accounts. I cannot tell why the failure occured here without the error log.

And, please pull the latest code and update the local version.

Thanks!

**Comment by adjebbar** [comment]
Hey.

I checked to error log, it shows:  
# TIMESTAMP OF THIS ARCHIVE: 2024-3-20 22:40:10
^[[31m╷^[[0m^[[0m
^[[31m│^[[0m ^[[0m^[[1m^[[31mError: ^[[0m^[[0m^[[1mcreating EC2 Instance: OptInRequired: **In order to use this AWS Marketplace product you need to accept terms and subscribe**. To do so please visit https://aws.amazon.com/marketplace/pp?sku=cvugziknvmxgqna9noibqnnsy
^[[31m│^[[0m ^[[0m      status code: 401, request id: 9bd4fc6b-bc72-4694-b156-12bb166b37c7^[[0m
......
I there other free linux dist other than centos?
Thinks

**Comment by zhenrong-wang** [comment]
> Hey.
> 
> I checked to error log, it shows:
> 
> # TIMESTAMP OF THIS ARCHIVE: 2024-3-20 22:40:10
> ^[[31m╷^[[0m^[[0m ^[[31m│^[[0m ^[[0m^[[1m^[[31mError: ^[[0m^[[0m^[[1mcreating EC2 Instance: OptInRequired: **In order to use this AWS Marketplace product you need to accept terms and subscribe**. To do so please visit https://aws.amazon.com/marketplace/pp?sku=cvugziknvmxgqna9noibqnnsy ^[[31m│^[[0m ^[[0m status code: 401, request id: 9bd4fc6b-bc72-4694-b156-12bb166b37c7^[[0m ...... I there other free linux dist other than centos? Thinks


Hi,

Here are the reasons behind this problem:

1. AWS doesn't provide CentOS Linux directly (only through the marketplace), but HPC-NOW needs this Linux to install the nodes.
2. The CentOS images on AWS are free of charge. 
3. The only thing you need to do is a free subscription.

So, here is the solution (it is in ./docs/UserManual-EN.pdf on Page 13).

If you are using Amazon Web Services global regions (NOT China regions), you MUST subscribe the CentOS 7.9 and CentOS Stream 9 AMIs to your AWS account before initializing any clusters. Please visit the [AWS Marketplace](https://aws.amazon.com/marketplace) and search **CentOS**, then choose **Amazon Web Services** as the publisher. 

Then, select **CentOS Stream 9 (x86_64)** and **CentOS 7 (x86_64) - with Updates HVM** and subscribe them respectively. 

Hope it helps. Thanks!

**Comment by adjebbar** [comment]
Ok it works now

**Comment by zhenrong-wang** [comment]
> Ok it works now

Good to know.

**Comment by adjebbar** [comment]
I have a other question but not related to this issue. it's about https://console.hpc-now.com/auth/login?pathAuth=true&path=%2Fdashboard. How ca I set up such webinterface? 

Thnaks.

**Comment by zhenrong-wang** [comment]
This console is for the commercial users of Shanghai HPC-NOW Co., Ltd. 

And it has not been integrated with this open-source project yet.

**Comment by zhenrong-wang** [comment]
@adjebbar This issue should be resolved. I will be closing it soon. Any further questions, please submit other issues. Thanks!
